#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="3.4.1"
URL="https://github.com/joomla/joomla-cms/releases/download/$VERSION/Joomla_$VERSION-Stable-Full_Package.tar.gz"

dl $URL /usr/local/src

