#!/bin/bash -e
# regenerate joomla secret key and mysql password

. /etc/default/inithooks

PASSWORD=$(mcookie)

CONF=/var/www/joomla/configuration.php
sed -i "s|secret = \(.*\)|secret = '$(mcookie)';|" $CONF

sed -i "s|password = \(.*\)|password = '$PASSWORD';|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=joomla --pass="$PASSWORD"

